import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Compass, Database, FolderOpen, Github, MessageCircle, Rocket, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { competitions } from "@/lib/competitions";
import { CompetitionCard } from "@/components/CompetitionCard";

const problemCards = [
  [Search, "不再四处寻找竞赛信息", "集中整理官网、报名时间、规则文件、报名要求与备赛周期。"],
  [MessageCircle, "让学长学姐的经验留下来", "保存真实的备赛建议、技术路线、答辩经验和踩坑记录。"],
  [FolderOpen, "让优秀项目继续产生价值", "在作者授权下分享代码、报告、PPT 与作品，让知识持续流动。"],
  [Compass, "降低第一次参赛的门槛", "帮助第一次参赛的同学理解比赛、找到方向、迈出第一步。"]
];
export default function Home() { return <>
  <section className="hero"><div className="hero-pattern"/><div className="sysu-watermark" aria-hidden="true"/><div className="shell hero-grid"><div className="hero-copy"><span className="eyebrow"><Sparkles size={15}/> 学生共建 · 非官方平台</span><div className="hero-institution">中山大学智能工程学院<br/><strong>竞赛信息平台</strong></div><h1>让竞赛信息<br/>不再成为<span>信息差</span></h1><p>汇集竞赛时间、报名要求、备赛建议、开源项目、历届作品与真实参赛经验，让每一位想参加竞赛的同学，都更容易找到自己的起点。</p><div className="hero-actions"><Link className="button" href="/competitions">浏览全部竞赛 <ArrowRight size={18}/></Link><Link className="button ghost" href="/calendar"><CalendarDays size={18}/> 查看竞赛日历</Link></div><div className="quick"><span>热门方向</span>{["智能车", "RoboMaster", "数学建模", "AI", "嵌入式"].map(t => <Link key={t} href={`/competitions?q=${t}`}>{t}</Link>)}</div></div><div className="hero-panel"><div className="blueprint"><div className="bp-orbit one"/><div className="bp-orbit two"/><div className="bp-core">ISE<small>COMPETITION<br/>KNOWLEDGE BASE</small></div><span className="bp-label l1">DISCOVER / 发现</span><span className="bp-label l2">COMPETE / 参赛</span><span className="bp-label l3">SHARE / 分享</span></div><div className="hero-stat"><div><b>29</b><span>项学院支持竞赛</span></div><div><b>11</b><span>个技术方向</span></div><div><b>∞</b><span>等待沉淀的经验</span></div></div></div></div></section>
  <section className="developer-credit developer-credit-top"><div className="shell"><span>DEVELOPED & MAINTAINED BY</span><p>开发者：<strong>石宇轩</strong><i>×</i><strong>陈志亮</strong></p><p className="idea-credit">感谢 <strong>林楗棋</strong>、<strong>卢栎焕</strong> 为网站创建提供思路与建议</p><div className="developer-links"><Link href="/contact">联系网站维护者 <ArrowRight/></Link><Link href="/contributors">查看贡献者名单 <ArrowRight/></Link></div></div></section>
  <section className="section intro"><div className="shell split"><div className="section-heading sticky"><span className="kicker">WHY WE BUILD</span><h2>我们为什么想做<br/>这件事？</h2><p>不是缺少热情，而是缺少一个清晰的起点。</p></div><div className="story"><p className="lead">对很多第一次接触学科竞赛的同学来说，真正困难的往往不是“要不要参加”，而是<strong>“从哪里开始”</strong>。</p><p>中山大学的工科竞赛建设相较一些起步更早、长期积累更成熟的高校仍处于持续发展阶段，竞赛整体实力也还有较大的提升空间。建立这个平台，不是为了做简单比较，而是希望把分散的资源组织起来，为每一位想参加相关竞赛的同学提供更清晰、更详细的支持。</p><p>这里将持续整理比赛时间、报名材料与规则，沉淀学长学姐的评价、建议和交流记录，并在获得授权后共享往届优秀作品，让一次参赛真正成为下一届可以继承的经验。</p><p>比赛什么时候报名？应该提前多久准备？需要学习哪些技术？怎样找到合适的队友？这些信息往往散落在官网、通知、群聊、GitHub，以及一届又一届同学的电脑和聊天记录里。</p><div className="principle"><span>因此，我们想把</span><b>零散信息 → 集中整理</b><b>个人经验 → 共同知识</b><b>一次作品 → 长期价值</b></div></div></div></section>
  <section className="section problems"><div className="shell"><div className="center-heading"><span className="kicker">WHAT WE SOLVE</span><h2>我们希望解决什么问题？</h2><p>从找到一场比赛，到真正完成一次参赛。</p></div><div className="problem-grid">{problemCards.map(([Icon, title, text], i) => { const C = Icon as typeof Search; return <article key={title as string}><span className="problem-no">0{i+1}</span><C/><h3>{title as string}</h3><p>{text as string}</p></article>})}</div></div></section>
  <section className="section journey"><div className="shell"><span className="kicker light">A SHARED JOURNEY</span><h2>我们希望它最终成为……</h2><p>不是一份“比赛名单”，而是一份由一届又一届同学共同积累起来的竞赛知识库。</p><div className="journey-grid"><div><Search/><b>发现</b><span>知道有哪些选择，找到与你兴趣和能力相匹配的比赛。</span></div><ArrowRight/><div><Rocket/><b>参赛</b><span>读懂规则、规划周期、寻找队友，少走一些弯路。</span></div><ArrowRight/><div><Users/><b>分享</b><span>留下经验与作品，让下一届从更高的起点出发。</span></div></div></div></section>
  <section className="slogan-section"><div className="shell"><span>ISE COMPETITION HUB</span><blockquote>让这一届走过的路，<br/><strong>成为下一届出发的地方。</strong></blockquote><p>发现比赛 · 认真参赛 · 留下经验</p></div></section>
  <section className="section"><div className="shell"><div className="section-title-row"><div><span className="kicker">EXPLORE</span><h2>29 项学院支持竞赛</h2><p>先从这些值得关注的竞赛开始，时间与规则以官方最新通知为准。</p></div><Link href="/competitions">查看全部 <ArrowRight size={17}/></Link></div><div className="card-grid featured">{competitions.slice(0, 6).map(c => <CompetitionCard key={c.slug} item={c}/>)}</div></div></section>
  <section className="section picker"><div className="shell picker-inner"><div><span className="kicker">NOT SURE YET?</span><h2>还不知道参加什么比赛？</h2><p>从你感兴趣的方向开始。无需先成为高手，选择一个目标，本身就是开始。</p></div><div className="direction-cloud">{["人工智能与算法", "软件与程序设计", "机器人", "智能车与无人系统", "嵌入式与芯片", "数学与建模", "交通运输", "信息安全", "创新创业"].map(x => <Link key={x} href="/competitions">{x}</Link>)}</div></div></section>
  <section className="section contribute"><div className="shell contribute-box"><div className="contribute-copy"><span className="kicker light">BUILD TOGETHER</span><h2>欢迎一起把这里建设得更好</h2><p>一条时间更新、一个有用的开源链接，或一句给下一届同学的建议，都可能帮助后来的人少走很长一段弯路。</p><div className="trust"><ShieldCheck/> 经验和文件提交后立即公开；请确认分享权并移除隐私信息。</div></div><div className="contribute-actions"><Link href="/contribute?type=experience"><MessageCircle/>分享参赛经验<ArrowRight/></Link><Link href="/contribute?type=project"><Github/>上传优秀作品<ArrowRight/></Link><Link href="/contribute?type=information"><Database/>补充竞赛信息<ArrowRight/></Link></div></div></section>
  <section className="sources"><div className="shell source-inner"><BookOpen/><div><h3>关于信息来源与真实性</h3><p>本站优先引用赛事官网、主办方通知及学院正式文件。尚未核验的信息会明确标注“待核验”或“暂无可靠信息”，宁可留白，也不编造。</p></div><Link href="/about">了解我们的原则</Link></div></section>
  </> }
