"use client";
import { useEffect, useState } from "react";
import { Download, FileArchive, LoaderCircle, MessageCircle, Send, UserRound } from "lucide-react";
type Project={id:string;title:string;content:string;type:string;license:string|null;created_at:string;files:Array<{name:string;mimeType:string|null;url:string|null}>};
type Message={id:string;display_name:string;content:string;created_at:string};
type Data={configured:boolean;projects:Project[];messages:Message[]};
export function CompetitionCommunity({slug}:{slug:string}){const[data,setData]=useState<Data|null>(null);const[name,setName]=useState("");const[content,setContent]=useState("");const[status,setStatus]=useState("");const[sending,setSending]=useState(false);useEffect(()=>{fetch(`/api/competitions/${slug}/community`).then(r=>r.json()).then(setData).catch(()=>setData({configured:false,projects:[],messages:[]}))},[slug]);async function submit(e:React.FormEvent){e.preventDefault();setSending(true);setStatus("");const submittedName=name.trim()||"匿名访客";const submittedContent=content.trim();try{const r=await fetch(`/api/competitions/${slug}/community`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({displayName:submittedName,content:submittedContent})});const result=await r.json();setStatus(result.message??result.error);if(r.ok)setContent("")}catch{setStatus("网络异常，请稍后再试")}finally{setSending(false)}}return <>
  <section><div className="live-title"><h2><FileArchive/>过来人的项目参考</h2><span>来自审核通过的经验与作品投稿</span></div>{!data?<div className="live-loading"><LoaderCircle className="spin"/>正在读取项目参考…</div>:data.projects.length?<div className="alumni-projects">{data.projects.map(project=><article key={project.id}><span>{project.type==="project"?"优秀作品":"参赛经验"}</span><h3>{project.title}</h3><p>{project.content.slice(0,220)}{project.content.length>220?"…":""}</p><div className="project-files">{project.files.map(file=>file.url?<a href={file.url} key={file.name} target="_blank" rel="noopener noreferrer"><Download/>{file.name}</a>:<span key={file.name}><FileArchive/>{file.name}（暂不可下载）</span>)}</div><small>{new Date(project.created_at).toLocaleDateString("zh-CN")} · {project.license||"投稿者保留权利"}</small></article>)}</div>:<div className="empty-inline"><FileArchive/><div><b>暂时还没有同学分享项目文件</b><p>{data.configured?"审核通过的经验投稿与附件会自动出现在这里。":"配置 Supabase 并执行数据库迁移后，本栏目将动态读取投稿。"}</p></div></div>}</section>
  <section><div className="live-title"><h2><MessageCircle/>关于这项竞赛的讨论</h2><span>无需登录 · 审核后公开</span></div><div className="discussion-layout"><div className="message-list">{data?.messages.length?data.messages.map(message=><article key={message.id}><div><UserRound/><b>{message.display_name}</b><time>{new Date(message.created_at).toLocaleString("zh-CN")}</time></div><p>{message.content}</p></article>):<div className="discussion-empty">还没有审核通过的留言，欢迎提出问题或分享观点。</div>}</div><form onSubmit={submit} className="message-form"><label>显示昵称（选填）<input value={name} onChange={e=>setName(e.target.value)} maxLength={30} placeholder="不填写则显示匿名访客"/></label><label>你的留言<textarea value={content} onChange={e=>setContent(e.target.value)} minLength={2} maxLength={1000} required rows={5} placeholder="讨论规则理解、组队、备赛方法或参赛体验…"/></label><button className="button" disabled={sending}>{sending?<LoaderCircle className="spin"/>:<Send/>}提交留言</button>{status&&<p className="form-status">{status}</p>}<small>留言将由维护团队审核后公开，请保持友善并避免填写个人隐私信息。</small></form></div></section>
  </>}
