import { NextResponse } from "next/server";
import { getCompetition } from "@/lib/competitions";
import { getCommunity } from "@/lib/community";
import { getSupabaseAdmin } from "@/lib/supabase/admin";

export const runtime="nodejs";export const dynamic="force-dynamic";
const attempts=new Map<string,{count:number;reset:number}>();
const clean=(value:unknown,max:number)=>typeof value==="string"?value.trim().slice(0,max):"";
export async function GET(_:Request,{params}:{params:Promise<{slug:string}>}){const{slug}=await params;if(!getCompetition(slug))return NextResponse.json({error:"Competition not found"},{status:404});try{const data=await getCommunity(slug);if(data===null)return NextResponse.json({error:"竞赛尚未同步到数据库"},{status:404});return NextResponse.json(data,{headers:{"Cache-Control":"no-store"}})}catch{return NextResponse.json({error:"社区内容读取失败",configured:true,projects:[],messages:[]},{status:500})}}
export async function POST(request:Request,{params}:{params:Promise<{slug:string}>}){const{slug}=await params;if(!getCompetition(slug))return NextResponse.json({error:"Competition not found"},{status:404});const admin=getSupabaseAdmin();if(!admin)return NextResponse.json({error:"网站社区服务尚未配置"},{status:503});const ip=request.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||request.headers.get("x-real-ip")||"local";const now=Date.now();const rate=attempts.get(ip);if(rate&&rate.reset>now&&rate.count>=8)return NextResponse.json({error:"提交较频繁，请稍后再试"},{status:429});attempts.set(ip,{count:rate&&rate.reset>now?rate.count+1:1,reset:now+600000});let body:unknown;try{body=await request.json()}catch{return NextResponse.json({error:"请求格式不正确"},{status:400})}const record=body as Record<string,unknown>;const displayName=clean(record.displayName,30)||"匿名访客";const content=clean(record.content,1000);if(content.length<2)return NextResponse.json({error:"留言至少需要 2 个字符"},{status:400});const competition=await admin.from("competitions").select("id").eq("slug",slug).eq("status","approved").maybeSingle();if(competition.error||!competition.data)return NextResponse.json({error:"竞赛数据尚未就绪"},{status:503});const result=await admin.from("discussion_messages").insert({competition_id:competition.data.id,author_id:null,display_name:displayName,content,status:"pending"});if(result.error)return NextResponse.json({error:"留言提交失败，请稍后重试"},{status:500});return NextResponse.json({ok:true,message:"留言已提交，审核通过后会公开显示"},{status:201})}
