import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import path from "node:path";
import { getCompetition } from "@/lib/competitions";
import { getSupabaseAdmin } from "@/lib/supabase/admin";
export const runtime="nodejs";export const dynamic="force-dynamic";
const MAX_FILE_SIZE=10*1024*1024,MAX_FILES=5;
const allowed=new Map<string,Set<string>>([[".pdf",new Set(["application/pdf"])],[".docx",new Set(["application/vnd.openxmlformats-officedocument.wordprocessingml.document"])],[".pptx",new Set(["application/vnd.openxmlformats-officedocument.presentationml.presentation"])],[".xlsx",new Set(["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"])],[".zip",new Set(["application/zip","application/x-zip-compressed"])],[".png",new Set(["image/png"])],[".jpg",new Set(["image/jpeg"])],[".jpeg",new Set(["image/jpeg"])],[".txt",new Set(["text/plain"])]]);
const text=(form:FormData,name:string,max:number)=>String(form.get(name)??"").trim().slice(0,max);const emailPattern=/^[^\s@]{1,64}@[^\s@]{1,190}\.[^\s@]{2,}$/;
export async function POST(request:Request){const admin=getSupabaseAdmin();if(!admin)return NextResponse.json({error:"投稿服务尚未配置，请联系维护者"},{status:503});let form:FormData;try{form=await request.formData()}catch{return NextResponse.json({error:"无法读取提交内容"},{status:400})}const slug=text(form,"competition",80);if(!getCompetition(slug))return NextResponse.json({error:"请选择有效竞赛"},{status:400});const title=text(form,"title",100),content=text(form,"content",5000),award=text(form,"award",80),contributorName=text(form,"contributorName",40),email=text(form,"email",254);if(title.length<2||content.length<10||!award)return NextResponse.json({error:"请完整填写标题、获奖等级和至少 10 个字符的经验内容"},{status:400});if(email&&!emailPattern.test(email))return NextResponse.json({error:"邮箱格式不正确"},{status:400});const files=form.getAll("files").filter((item):item is File=>item instanceof File&&item.size>0);if(!files.length||files.length>MAX_FILES)return NextResponse.json({error:"请上传 1 至 5 个文件"},{status:400});for(const file of files){const ext=path.extname(file.name).toLowerCase(),mimes=allowed.get(ext);if(file.size>MAX_FILE_SIZE)return NextResponse.json({error:`${file.name} 超过 10MB`},{status:400});if(!mimes||!mimes.has(file.type.toLowerCase()))return NextResponse.json({error:`${file.name} 的扩展名或文件类型不受支持`},{status:400})}const competition=await admin.from("competitions").select("id").eq("slug",slug).eq("status","approved").maybeSingle();if(competition.error||!competition.data)return NextResponse.json({error:"竞赛数据尚未同步，请联系维护者"},{status:503});const submission=await admin.from("submissions").insert({author_id:null,competition_id:competition.data.id,type:"experience",title,content,award,contributor_name:contributorName||null,status:"pending",license:"投稿者授权本站在审核通过后公开分享"}).select("id").single();if(submission.error)return NextResponse.json({error:"投稿记录创建失败"},{status:500});const submissionId=submission.data.id as string,uploaded:string[]=[];try{if(email){const contact=await admin.from("submission_contacts").insert({submission_id:submissionId,email});if(contact.error)throw contact.error}const metadata=[];for(const file of files){const ext=path.extname(file.name).toLowerCase(),storagePath=`${submissionId}/${randomUUID()}${ext}`;const upload=await admin.storage.from("submission-files").upload(storagePath,await file.arrayBuffer(),{contentType:file.type,upsert:false});if(upload.error)throw upload.error;uploaded.push(storagePath);metadata.push({submission_id:submissionId,storage_path:storagePath,original_name:path.basename(file.name).slice(0,255),mime_type:file.type,size_bytes:file.size})}const records=await admin.from("submission_files").insert(metadata);if(records.error)throw records.error;return NextResponse.json({ok:true,id:submissionId,slug,status:"pending"},{status:201})}catch{if(uploaded.length)await admin.storage.from("submission-files").remove(uploaded);await admin.from("submissions").delete().eq("id",submissionId);return NextResponse.json({error:"文件上传失败，未保存不完整的投稿，请稍后重试"},{status:500})}}
