import { NextResponse } from "next/server";
import { randomUUID } from "node:crypto";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { getCompetition } from "@/lib/competitions";
import { addProject } from "@/lib/local-community";
export const runtime="nodejs";export const dynamic="force-dynamic";
const allowed=new Map([[".pdf","application/pdf"],[".docx","application/vnd.openxmlformats-officedocument.wordprocessingml.document"],[".pptx","application/vnd.openxmlformats-officedocument.presentationml.presentation"],[".xlsx","application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],[".zip","application/zip"],[".png","image/png"],[".jpg","image/jpeg"],[".jpeg","image/jpeg"],[".txt","text/plain"],[".md","text/markdown"]]);
export async function POST(request:Request){try{const form=await request.formData();const slug=String(form.get("competition")??"");if(!getCompetition(slug))return NextResponse.json({error:"请选择有效竞赛"},{status:400});const title=String(form.get("title")??"").trim().slice(0,100);const content=String(form.get("content")??"").trim().slice(0,5000);const award=String(form.get("award")??"").trim().slice(0,80);const contributorName=String(form.get("contributorName")??"").trim().slice(0,40);const email=String(form.get("email")??"").trim().slice(0,120);if(!title||!content||!award)return NextResponse.json({error:"请填写标题、获奖等级和经验内容"},{status:400});if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return NextResponse.json({error:"邮箱格式不正确"},{status:400});const entries=form.getAll("files").filter((item):item is File=>item instanceof File&&item.size>0);if(entries.length>5)return NextResponse.json({error:"每次最多上传 5 个文件"},{status:400});const files=[];const uploadDir=path.join(process.cwd(),"public","uploads");await mkdir(uploadDir,{recursive:true});for(const file of entries){if(file.size>10*1024*1024)return NextResponse.json({error:`${file.name} 超过 10MB`},{status:400});const ext=path.extname(file.name).toLowerCase();if(!allowed.has(ext))return NextResponse.json({error:`不支持 ${ext||"未知"} 文件，请上传 PDF、Office、ZIP、图片或文本`},{status:400});const storedName=`${randomUUID()}${ext}`;await writeFile(path.join(uploadDir,storedName),Buffer.from(await file.arrayBuffer()));files.push({name:path.basename(file.name),url:`/uploads/${storedName}`,mimeType:file.type||allowed.get(ext)!})}const id=randomUUID();await addProject({id,slug,title,content,award,contributorName:contributorName||undefined,email:email||undefined,createdAt:new Date().toISOString(),files});return NextResponse.json({ok:true,id,slug},{status:201})}catch{return NextResponse.json({error:"提交失败，请稍后重试"},{status:500})}}
