create extension if not exists pgcrypto;
create type public.app_role as enum ('user','moderator','admin');
create type public.review_status as enum ('draft','pending','approved','rejected');

create table public.profiles (id uuid primary key references auth.users on delete cascade, nickname text not null check(char_length(nickname) between 1 and 40), avatar_url text, bio text check(char_length(bio)<=300), real_name text, show_real_name boolean not null default false, role app_role not null default 'user', created_at timestamptz not null default now());
create table public.competitions (id bigint generated always as identity primary key, slug text unique not null, name text not null, summary text, tags text[] not null default '{}', difficulty text, preparation_cycle text, official_url text, status review_status not null default 'approved', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.competition_editions (id bigint generated always as identity primary key, competition_id bigint not null references public.competitions on delete cascade, year int not null, registration_start date, registration_end date, event_start date, event_end date, source_url text, verified_at timestamptz, unique(competition_id,year));
create table public.information_sources (id bigint generated always as identity primary key, competition_id bigint references public.competitions on delete cascade, title text not null, url text not null, source_type text not null, checked_at timestamptz, is_official boolean not null default false);
create table public.registration_requirements (id bigint generated always as identity primary key, edition_id bigint not null references public.competition_editions on delete cascade, content text not null, source_url text);
create table public.external_resources (id bigint generated always as identity primary key, competition_id bigint not null references public.competitions on delete cascade, title text not null, url text not null, resource_type text not null, license text, status review_status not null default 'pending');
create table public.submissions (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles on delete cascade, competition_id bigint references public.competitions on delete set null, type text not null check(type in ('experience','project','information')), title text not null, content text not null, license text, status review_status not null default 'pending', reviewed_by uuid references public.profiles, created_at timestamptz not null default now());
create table public.submission_files (id uuid primary key default gen_random_uuid(), submission_id uuid not null references public.submissions on delete cascade, storage_path text not null, original_name text not null, mime_type text, size_bytes bigint, created_at timestamptz not null default now());
create table public.comments (id uuid primary key default gen_random_uuid(), author_id uuid not null references public.profiles on delete cascade, competition_id bigint not null references public.competitions on delete cascade, parent_id uuid references public.comments on delete cascade, content text not null check(char_length(content) between 1 and 3000), status review_status not null default 'approved', created_at timestamptz not null default now());
create table public.comment_votes (user_id uuid references public.profiles on delete cascade, comment_id uuid references public.comments on delete cascade, created_at timestamptz not null default now(), primary key(user_id,comment_id));
create table public.bookmarks (user_id uuid references public.profiles on delete cascade, competition_id bigint references public.competitions on delete cascade, created_at timestamptz not null default now(), primary key(user_id,competition_id));
create table public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid references public.profiles on delete set null, target_type text not null, target_id text not null, reason text not null, status review_status not null default 'pending', created_at timestamptz not null default now());
create table public.corrections (id uuid primary key default gen_random_uuid(), author_id uuid references public.profiles on delete set null, competition_id bigint not null references public.competitions on delete cascade, content text not null, source_url text, status review_status not null default 'pending', created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.competitions enable row level security; alter table public.competition_editions enable row level security; alter table public.information_sources enable row level security; alter table public.registration_requirements enable row level security; alter table public.external_resources enable row level security; alter table public.submissions enable row level security; alter table public.submission_files enable row level security; alter table public.comments enable row level security; alter table public.comment_votes enable row level security; alter table public.bookmarks enable row level security; alter table public.reports enable row level security; alter table public.corrections enable row level security;
create function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role in ('moderator','admin')) $$;
create policy "public approved competitions" on public.competitions for select using(status='approved');
create policy "public editions" on public.competition_editions for select using(true); create policy "public sources" on public.information_sources for select using(true); create policy "public requirements" on public.registration_requirements for select using(true); create policy "public approved resources" on public.external_resources for select using(status='approved');
create policy "public profiles" on public.profiles for select using(true); create policy "own profile update" on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy "approved submissions or own" on public.submissions for select using(status='approved' or author_id=auth.uid() or public.is_staff()); create policy "create own submission" on public.submissions for insert with check(author_id=auth.uid()); create policy "update own draft" on public.submissions for update using(author_id=auth.uid() and status in ('draft','rejected'));
create policy "approved comments" on public.comments for select using(status='approved' or author_id=auth.uid() or public.is_staff()); create policy "create own comment" on public.comments for insert with check(author_id=auth.uid()); create policy "delete own comment" on public.comments for delete using(author_id=auth.uid());
create policy "own votes" on public.comment_votes for all using(user_id=auth.uid()) with check(user_id=auth.uid()); create policy "own bookmarks" on public.bookmarks for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "create correction" on public.corrections for insert with check(author_id=auth.uid()); create policy "read own correction" on public.corrections for select using(author_id=auth.uid() or public.is_staff()); create policy "create report" on public.reports for insert with check(reporter_id=auth.uid());
create policy "staff manage competitions" on public.competitions for all using(public.is_staff()) with check(public.is_staff()); create policy "staff manage submissions" on public.submissions for all using(public.is_staff()) with check(public.is_staff());
