insert into public.competitions(slug,name,summary,tags,difficulty,preparation_cycle,official_url,status) values
('siemens-cup','“西门子杯”中国智能制造挑战赛','面向智能制造系统设计、控制与工程实践的综合赛事。',array['智能制造','自动控制'],'进阶','建议关注官方通知','https://www.siemenscup-cimc.org.cn/','approved'),
('china-software-cup','“中国软件杯”大学生软件设计大赛','围绕产业命题开展软件设计与工程实现。',array['软件','程序设计'],'进阶','建议提前一学期','https://www.cnsoftbei.com/','approved'),
('challenge-cup','“挑战杯”中国大学生创业计划竞赛','以创业计划、社会价值与综合展示为核心。',array['创新创业'],'挑战','建议长期准备','https://www.tiaozhanbei.net/','approved'),
('acm-icpc','ACM-ICPC 国际大学生程序设计竞赛','强调算法、数据结构与团队协作的程序设计竞赛。',array['算法','程序设计'],'挑战','建议长期训练','https://icpc.global/','approved'),
('huawei-ict','华为 ICT 大赛','覆盖网络、云与计算等 ICT 技术方向。',array['ICT','云计算','人工智能'],'进阶','建议关注官方赛季','https://e.huawei.com/cn/talent/ict-academy/#/ict-contest','approved'),
('lanqiao-cup','蓝桥杯全国软件和信息技术专业人才大赛','包含软件、电子等方向的个人与团队赛事。',array['程序设计','嵌入式'],'入门','建议提前 2–4 个月','https://dasai.lanqiao.cn/','approved'),
('mcm-icm','美国大学生数学建模竞赛','以团队形式完成开放问题建模、求解与英文论文写作。',array['数学建模','数据分析'],'进阶','建议提前 3–6 个月','https://contest.comap.com/undergraduate/contests/mcm/','approved'),
('innovation-annual','全国大学生创新创业训练计划年会展示','集中展示大学生创新训练项目成果。',array['创新创业','科研实践'],'进阶','依托项目长期积累','http://gjcxcy.bjtu.edu.cn/','approved'),
('robot-competition','全国大学生机器人大赛','包含 RoboMaster、RoboCon 等机器人赛事。',array['机器人','自动控制'],'挑战','建议提前 6–12 个月','https://www.robomaster.com/','approved'),
('computer-system','全国大学生计算机系统能力大赛','聚焦操作系统、编译、芯片等系统能力。',array['计算机系统','程序设计'],'挑战','建议提前一学期','https://os.educg.net/','approved'),
('transport-tech','全国大学生交通运输科技大赛','面向交通运输领域的科技创新与工程应用。',array['交通运输','创新'],'进阶','建议提前一学期','https://www.nactrans.com.cn/','approved'),
('embedded-chip','全国大学生嵌入式芯片与系统设计竞赛','围绕嵌入式芯片、系统软硬件协同设计。',array['嵌入式','芯片'],'挑战','建议提前 4–8 个月','http://www.socchina.net/','approved'),
('cn-math-modeling','全国大学生数学建模竞赛','通过三人团队完成实际问题建模与论文写作。',array['数学建模','数据分析'],'进阶','建议提前 3–6 个月','https://www.mcm.edu.cn/','approved'),
('statistics-modeling','全国大学生统计建模大赛','使用统计方法分析真实问题并形成研究成果。',array['统计建模','数据分析'],'进阶','建议提前 3–6 个月','http://tjjmds.ai-learning.net/','approved'),
('information-security','全国大学生信息安全竞赛','聚焦网络安全创新实践与技术能力。',array['信息安全','网络'],'挑战','建议提前一学期','https://www.ciscn.cn/','approved'),
('security-confrontation','全国大学生信息安全与对抗技术竞赛','强调信息安全与对抗技术的实践应用。',array['信息安全','攻防'],'挑战','建议提前一学期','http://www.isclab.org.cn/','approved'),
('smart-car','全国大学生智能汽车竞赛','融合感知、控制、嵌入式与车辆系统的工程竞赛。',array['智能车','嵌入式','自动控制'],'挑战','建议提前 6–10 个月','https://smartcar.cdstm.cn/','approved'),
('ai-algorithm','全球校园人工智能算法精英大赛','围绕人工智能算法及产业问题开展竞赛。',array['人工智能','算法'],'进阶','建议提前 2–4 个月','https://www.aicomp.cn/','approved'),
('raicom','睿抗机器人开发者大赛（RAICOM）','聚焦机器人开发、算法与综合应用。',array['机器人','人工智能'],'进阶','建议提前 3–6 个月','https://www.robocom.com.cn/','approved'),
('future-designer','未来设计师·全国高校数字艺术设计大赛','面向数字艺术、交互与创新设计成果。',array['数字创意','交互设计'],'入门','建议提前 2–4 个月','https://www.ncda.org.cn/','approved'),
('apmcm','亚太地区大学生数学建模竞赛','面向亚太高校学生的数学建模赛事。',array['数学建模','数据分析'],'进阶','建议提前 2–4 个月','https://www.apmcm.org/','approved'),
('mechanical-innovation','中国大学生机械工程创新创意大赛','以机械工程创新、设计与实践为核心。',array['机械','智能制造'],'进阶','建议提前一学期','http://www.gczbds.org/','approved'),
('computer-design','中国大学生计算机设计大赛','覆盖软件应用、信息可视化、人工智能等方向。',array['计算机','数字创意'],'进阶','建议提前 3–6 个月','https://jsjds.blcu.edu.cn/','approved'),
('college-computer','中国高校计算机大赛','包含大数据、团体程序设计、移动应用、网络技术与 AI 创意等赛道。',array['计算机','人工智能','大数据'],'进阶','依赛道而定','https://www.c4best.cn/','approved'),
('robot-creative','中国高校智能机器人创意大赛','围绕智能机器人创意、设计和系统实现。',array['机器人','创新创意'],'进阶','建议提前一学期','http://www.robotcontest.cn/','approved'),
('robocup-china','中国机器人大赛暨 RoboCup 机器人世界杯中国赛','机器人足球、服务机器人等多方向综合赛事。',array['机器人','人工智能'],'挑战','建议提前 6–12 个月','http://crc.drct-caa.org.cn/','approved'),
('robot-ai','中国机器人及人工智能大赛','聚焦机器人系统与人工智能融合应用。',array['机器人','人工智能'],'进阶','建议提前 3–8 个月','https://www.caairobot.com/','approved'),
('china-us-maker','中美青年创客大赛','鼓励跨学科团队以创新方案回应社会议题。',array['创新创业','创客'],'进阶','建议提前 2–4 个月','https://chinaus-maker.cscse.edu.cn/','approved'),
('guangdong-ai-transport','广东省“AI+交通运输”创新应用大赛','探索人工智能在交通运输场景中的创新应用。',array['人工智能','交通运输'],'进阶','时间待官方核验','https://td.gd.gov.cn/','approved')
on conflict(slug) do update set name=excluded.name,summary=excluded.summary,tags=excluded.tags,difficulty=excluded.difficulty,preparation_cycle=excluded.preparation_cycle,official_url=excluded.official_url,status=excluded.status,updated_at=now();
